main: net.simplyvanilla.noillegals.NoIllegalsPlugin
name: NoIllegals
version: @version@
api-version: 1.19
folia-supported: true

author: Simply Vanilla
website: https://github.com/SimplyVanilla/NoIllegals
